bitcoin_json = {
    "bpi":{
       "EUR":{
          "code":"EUR",
          "description":"Euro",
          "rate":"815.8994",
          "rate_float":815.8994,
          "symbol":"&euro;"
       },
       "GBP":{
          "code":"GBP",
          "description":"British Pound Sterling",
          "rate":"677.4879",
          "rate_float":677.4879,
          "symbol":"&pound;"
       },
       "USD":{
          "code":"USD",
          "description":"United States Dollar",
          "rate":"728.4816",
          "rate_float":728.4816,
          "symbol":"&#36;"
       }
    },
    "chartName":"Bitcoin",
    "disclaimer":"This data was generated by creating random numbers and mimics the Coinbase API JSON response structure. It is NOT real data. DO NOT USE THIS TO TRADE CRYPTOCURRENCY!",
    "time":{
       "updatedISO":"2023-02-14T20:16:14.370072"
    }
 }

let bpi = bitcoin_json.bpi
let usedInfo = bpi.USD
let usd = 100

for (let currency in bpi){
    let data = bpi[currency]
    console.log(`${currency} ${data.description}`)
    //ToDO - inlude other infor about other currencies.
}

function convertUSD(){
    let usdExchangeRate = usedInfo.rate_float
    let exchangedValue = usdExchangeRate * usd

    return exchangedValue
}
let bitcoinEquivalent = convertUSD().toFixed(4)
console.log(bitcoinEquivalent)
console.log(`${usd} is equivalent to ${bitcoinEquivalent}`)








